/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

import com.itson.dao.AutomovilesDAO;
import com.itson.dao.LicenciasDAO;
import com.itson.dao.PersonasDAO;
import com.itson.dao.VehiculosDAO;
import com.itson.dominio.Automovil;
import com.itson.dominio.Persona;
import com.itson.interfaces.IAutomovilesDAO;
import com.itson.interfaces.ILicenciasDAO;
import com.itson.interfaces.IPersonasDAO;
import com.itson.interfaces.IVehiculosDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexa Soto(236348) y Rosalía Perez (233505)
 */
public class FrmAutoNuevo extends javax.swing.JFrame {

    IPersonasDAO personaDao = new PersonasDAO();
    ILicenciasDAO licenciaDao = new LicenciasDAO();
    IAutomovilesDAO autoDao = new AutomovilesDAO();
    IVehiculosDAO vehiculoDao = new VehiculosDAO();

    private String rfc, serie;

    /**
     * Constructor por defecto
     */
    public FrmAutoNuevo() {
        initComponents();
    }

    /**
     * Busca una persona por su rfc
     *
     * @param rfc RFC de la persona
     */
    public void buscarRfc(String rfc) {
        Persona persona = new Persona();
        persona = personaDao.consultar(rfc);
    }

    /**
     * Método que guarda las placas de un automóvil
     */
    private void guardarPlacas() {
        String rfc = this.txtRfc.getText();
        String color = this.txtColor.getText();
        String linea = this.txtLinea.getText();
        String modelo = this.txtModelo.getText();
        String serie = this.txtSerie.getText();
        String marca = this.txtMarca.getText();

        if (licenciaDao.consultar(rfc)) {
            Automovil auto = new Automovil();
            Persona persona = personaDao.consultar(rfc);

            //Validaciones
            if (vehiculoDao.buscar(serie) == null) {
                auto.setColor(color);
                auto.setLinea(linea);
                auto.setMarca(marca);
                auto.setModelo(modelo);
                auto.setNum_serie(serie);
                auto.setPersona(persona);
                autoDao.insertar(auto);

                //Abre el form de placas
                FrmPruebaPlacas frm = new FrmPruebaPlacas();
                frm.setVisible(true);
//                System.out.println(serie);
//                System.out.println(rfc);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Error con el número de serie");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Licencia vencida");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        lblModelo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        lblAutoNuevo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDatosAuto = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        lblSerie1 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        lblSerie2 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();

        btnSalir.setBackground(new java.awt.Color(255, 90, 130));
        btnSalir.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Placas para vehículo nuevo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModelo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblModelo.setText("Modelo:");
        getContentPane().add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        lblMarca.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblMarca.setText("Marca:");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        lblColor.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblColor.setText("Color:");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        lblLinea.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblLinea.setText("Linea:");
        getContentPane().add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        txtModelo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 170, -1));

        txtMarca.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 170, -1));

        txtColor.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 170, -1));

        txtLinea.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        getContentPane().add(txtLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 170, -1));

        lblAutoNuevo.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblAutoNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblAutoNuevo.setText("PLACAS: AUTO NUEVO");
        getContentPane().add(lblAutoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 90, 130));
        btnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 143, 143));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 90));

        lblDatosAuto.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        lblDatosAuto.setText("DATOS AUTOMOVIL");
        getContentPane().add(lblDatosAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        btnSalir1.setBackground(new java.awt.Color(255, 90, 130));
        btnSalir1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("SALIR");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, -1, -1));

        lblSerie1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblSerie1.setText("Núm. de serie:");
        getContentPane().add(lblSerie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtSerie.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerieKeyTyped(evt);
            }
        });
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 170, -1));

        lblSerie2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblSerie2.setText("RFC:");
        getContentPane().add(lblSerie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        txtRfc.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtRfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRfcKeyTyped(evt);
            }
        });
        getContentPane().add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 170, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        this.guardarPlacas();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        FrmPrincipal frmPrincial = new FrmPrincipal();
        frmPrincial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        FrmPrincipal frmPrincial = new FrmPrincipal();
        frmPrincial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void txtRfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcKeyTyped
        if (txtRfc.getText().length() >= 13) {
            evt.consume();
        }
        final char key = evt.getKeyChar();

        if (Character.isLowerCase(key) || (key == KeyEvent.VK_BACK_SPACE) || key == KeyEvent.VK_DELETE) {
            evt.setKeyChar(Character.toUpperCase(key));
        } else if (!(Character.isLetterOrDigit(key) || (key == KeyEvent.VK_BACK_SPACE) || key == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRfcKeyTyped

    private void txtSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerieKeyTyped
        // TODO add your handling code here:
         if (txtSerie.getText().length() >= 30) {
            evt.consume();
        }
        final char key = evt.getKeyChar();

        if (Character.isLowerCase(key) || (key == KeyEvent.VK_BACK_SPACE) || key == KeyEvent.VK_DELETE) {
            evt.setKeyChar(Character.toUpperCase(key));
        } else if (!(Character.isLetterOrDigit(key) || (key == KeyEvent.VK_BACK_SPACE) || key == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSerieKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutoNuevo;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDatosAuto;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblSerie1;
    private javax.swing.JLabel lblSerie2;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
