/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

import com.itson.dao.AutomovilesDAO;
import com.itson.dao.PlacasDAO;
import com.itson.dominio.Automovil;
import com.itson.dominio.Persona;
import com.itson.dominio.Placa;
import com.itson.interfaces.IAutomovilesDAO;
import com.itson.interfaces.IPlacasDAO;
import com.itson.utils.GeneracionPlacas;

/**
 *
 * @author 
 */
public class FrmAutoUsado extends javax.swing.JFrame {

    Persona persona = null;
    IAutomovilesDAO autosDAO = new AutomovilesDAO();
    IPlacasDAO placaDAO = new PlacasDAO();

    /**
     * Creates new form FrmAutoUsado
     */
    public FrmAutoUsado(Persona persona) {
        this.persona = persona;
        initComponents();
    }

    private void guardarPlacas(){
        String placas = this.txtPlacas.getText();
        GeneracionPlacas placa = new GeneracionPlacas();
        String placaNueva = placa.generarPlaca();
        float costo = 1000;
        
        Automovil autoConsulta = (Automovil) 
                autosDAO.consultar(this.txtSerie.getText());
        
//        placaDAO.actualizar(placas);
        placaDAO.insertar(placaNueva, autoConsulta, persona, costo);
        this.txtNumAlfa.setText(placaNueva);
        this.txtCosto.setText(String.valueOf(costo));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSerie = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblSerie = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNumAlfa = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        txtPlacas = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        btnPlacas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblNumAlfa1 = new javax.swing.JLabel();
        txtNumAlfa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Placa auto usado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, -1));

        lblMarca.setText("Marca:");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblModelo.setText("Modelo:");
        getContentPane().add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txtMarca.setEditable(false);
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, -1));

        txtModelo.setEditable(false);
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 120, -1));

        lblColor.setText("Color:");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtColor.setEditable(false);
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        lblSerie.setText("Núm. de serie:");
        getContentPane().add(lblSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel1.setText("Datos placas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        lblNumAlfa.setText("Placas:");
        getContentPane().add(lblNumAlfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        lblCosto.setText("Costo:");
        getContentPane().add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));
        getContentPane().add(txtPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 130, -1));

        txtCosto.setEditable(false);
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 130, -1));

        btnPlacas.setText("PLACAS");
        btnPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        jLabel2.setText("Datos automovil");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 26, -1, -1));

        lblNumAlfa1.setText("Número alfanúmerico:");
        getContentPane().add(lblNumAlfa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        txtNumAlfa.setEditable(false);
        getContentPane().add(txtNumAlfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String serie = this.txtSerie.getText();
        
        IPlacasDAO placaDAO = new PlacasDAO();
        
        Placa placa = (Placa) placaDAO.consultar(serie);

        //Se llenan los campos de texto de manera automática
        txtModelo.setText(placa.getVehiculo().getModelo());
        txtMarca.setText(placa.getVehiculo().getMarca());
        txtColor.setText(placa.getVehiculo().getColor());
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void btnPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacasActionPerformed
        // TODO add your handling code here:
        this.guardarPlacas();
    }//GEN-LAST:event_btnPlacasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPlacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNumAlfa;
    private javax.swing.JLabel lblNumAlfa1;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumAlfa;
    private javax.swing.JTextField txtPlacas;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
