/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

import com.itson.dao.LicenciasDAO;
import com.itson.dao.PersonasDAO;
import com.itson.dominio.Persona;
import com.itson.interfaces.ILicenciasDAO;
import com.itson.interfaces.IPersonasDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class FrmConsultaPersona extends javax.swing.JFrame {

    Persona persona = null;
    /**
     * Creates new form FrmConsultaLicencia
     */
    public FrmConsultaPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscarLicencia = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblInstruccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Licencia vigente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 143, 143));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarLicencia.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        lblBuscarLicencia.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarLicencia.setText("BUSCAR LICENCIA VIGENTE");
        jPanel1.add(lblBuscarLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 70));

        lblRfc.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblRfc.setText("RFC:");
        getContentPane().add(lblRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtRfc.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtRfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRfcKeyTyped(evt);
            }
        });
        getContentPane().add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 158, 210, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 90, 130));
        btnBuscar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        lblInstruccion.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        lblInstruccion.setText("Ingrese el RFC de la persona");
        getContentPane().add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String rfc = txtRfc.getText();
        ILicenciasDAO licenciaDAO = new LicenciasDAO();
        
        IPersonasDAO personaDAO = new PersonasDAO();
        Persona personaConsulta = personaDAO.consultar(rfc);
        
        boolean licencia = licenciaDAO.consultar(rfc);
        if (licencia) {
            FrmPlaca frm = new FrmPlaca(personaConsulta);
            frm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "No se encuentra una licencia activa");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtRfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcKeyTyped
        // TODO add your handling code here:
        if (this.txtRfc.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRfcKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuscarLicencia;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
}
