/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

import com.itson.dao.PersonasDAO;
import com.itson.dominio.Persona;
import com.itson.interfaces.IPersonasDAO;
import com.itson.interfaces.ITramitesDAO;
import com.itson.utils.FormatoPaginas;
import javax.persistence.PersistenceException;

/**
 *
 * @author 
 */
public class FrmConsulta2 extends javax.swing.JFrame {
    private final FormatoPaginas formato;
    IPersonasDAO personaDao = new PersonasDAO();
    ITramitesDAO tramiteDao = new 

    /**
     * Creates new form FrmConsulta2
     */
    public FrmConsulta2(String rfc)throws PersistenceException{
        Persona persona = personaDao.consultar(rfc);
        initComponents();
        this.formato = new FormatoPaginas(2, 0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
