package com.itson.presentacion;

import com.itson.dao.LicenciasDAO;
import com.itson.dao.PersonasDAO;
import com.itson.utils.TipoVigencia;
import com.itson.dominio.*;
import com.itson.interfaces.*;
import excepciones.PersistenciaException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class FrmLicencia extends javax.swing.JFrame {
//
//    Persona persona = null;
//    Licencia licencia = null;
//    TipoLicencia tipoLicencia;

    TipoVigencia numVig = new TipoVigencia();

    /**
     * Creates new form Licencia
     */
    public FrmLicencia() {
        initComponents();
        //Busca la lista anotada en el array de vigencias
        String[] vigencias = numVig.obtenerVigencias();
        //Construye el combo box
        DefaultComboBoxModel creador = new DefaultComboBoxModel(vigencias);
        //Se le enlaza las opciones de vigencias a la combo box
        cbxVigencia.setModel(creador);

    }

//    private void guardar() {
//        Licencia licencia = new Licencia();
//        if (this.chbxUnAño.isSelected() && this.chbxNo.isSelected()) {
//            licencia.setVigencia(1);
//            licencia.setCosto(600);
//            licencia.setTipo_licencia(TipoLicencia.NORMAL);
//        } else if (this.chbxUnAño.isSelected() && this.chbxSi.isSelected()) {
//            licencia.setVigencia(1);
//            licencia.setCosto(200);
//            licencia.setTipo_licencia(TipoLicencia.DISCAPACITADO);
//        } else if (this.chbxDosAños.isSelected() && this.chbxNo.isSelected()) {
//            licencia.setVigencia(2);
//            licencia.setCosto(900);
//            licencia.setTipo_licencia(TipoLicencia.NORMAL);
//        } else if (this.chbxDosAños.isSelected() && this.chbxSi.isSelected()) {
//            licencia.setVigencia(2);
//            licencia.setCosto(500);
//            licencia.setTipo_licencia(TipoLicencia.DISCAPACITADO);
//        } else if (this.chbxTresAños.isSelected() && this.chbxNo.isSelected()) {
//            licencia.setVigencia(3);
//            licencia.setCosto(1100);
//            licencia.setTipo_licencia(TipoLicencia.NORMAL);
//        } else if (this.chbxTresAños.isSelected() && this.chbxSi.isSelected()) {
//            licencia.setVigencia(3);
//            licencia.setCosto(700);
//            licencia.setTipo_licencia(TipoLicencia.DISCAPACITADO);
//        }
//        licenciaDAO.insertar(persona, licencia);
//        JOptionPane.showMessageDialog(this, "Se agrego la licencia: ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDatosLicencia = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApPaterno = new javax.swing.JLabel();
        lblApMaterno = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDiscapacitado = new javax.swing.JLabel();
        chbxSi = new javax.swing.JCheckBox();
        btnSiguiente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblVigencia = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        txtApPaterno = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        cbxVigencia = new javax.swing.JComboBox<>();
        txtApMaterno = new javax.swing.JTextField();
        lblDiscapacitado1 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDatosLicencia.setText("Datos de la licencia");
        jPanel1.add(lblDatosLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 148, -1));

        lblRfc.setText("RFC");
        jPanel1.add(lblRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 98, 148, -1));

        lblNombres.setText("NOMBRES");
        jPanel1.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 141, 148, -1));

        lblApPaterno.setText("APELLIDO PATERNO");
        jPanel1.add(lblApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 188, 148, -1));

        lblApMaterno.setText("APELLIDO MATERNO");
        jPanel1.add(lblApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 236, 148, -1));

        lblFechaNacimiento.setText("FECHA DE NACIMIENTO");
        jPanel1.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 279, 171, -1));

        lblTelefono.setText("TELÉFONO");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 148, -1));

        lblDiscapacitado.setText("COSTO:");
        jPanel1.add(lblDiscapacitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 148, -1));

        chbxSi.setText("SÍ");
        chbxSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxSiActionPerformed(evt);
            }
        });
        jPanel1.add(chbxSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 85, -1));

        btnSiguiente.setText("GUARDAR");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, -1, -1));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, -1, -1));

        lblVigencia.setText("VIGENCIA");
        jPanel1.add(lblVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 487, 148, -1));

        jLabel10.setText("Datos del solicitante");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 62, 148, -1));
        jPanel1.add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 94, 120, -1));

        txtApPaterno.setEditable(false);
        jPanel1.add(txtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 184, -1));

        txtFechaNac.setEditable(false);
        jPanel1.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 184, -1));

        txtCosto.setEditable(false);
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 184, -1));

        txtNombres.setEditable(false);
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 184, -1));

        cbxVigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Un año", "Dos años", "Tres años" }));
        cbxVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVigenciaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 220, -1));

        txtApMaterno.setEditable(false);
        jPanel1.add(txtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 184, -1));

        lblDiscapacitado1.setText("DISCAPACITADO");
        jPanel1.add(lblDiscapacitado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 541, 148, -1));

        txtTelefono.setEditable(false);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 184, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chbxSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbxSiActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:

        String rfc = txtRfc.getText();
        String nombre = txtNombres.getText();
        String apellidoPaterno = txtApPaterno.getText();
        String apellidoMaterno = txtApMaterno.getText();
        String fechaNac = txtFechaNac.getText();
        String telefono = txtTelefono.getText();

        //Conversor de texto a float
        if (!txtNombres.getText().isEmpty()) {

            float costo = Float.parseFloat(txtCosto.getText());
            int vig = 0;
//Opciones del combo box
            if (cbxVigencia.getSelectedItem().toString().equals("Un año")) {
                vig = 1;
            } else if (cbxVigencia.getSelectedItem().toString().equals("Dos años")) {
                vig = 2;
            } else if (cbxVigencia.getSelectedItem().toString().equals("Tres años")) {
                vig = 3;
            }

            boolean discapacitado = false;
            //Opcición de discapacidad
            if (chbxSi.isSelected() == false) {
                discapacitado = false;
            } else if (chbxSi.isSelected() == true) {
                discapacitado = true;
            }
            
            ILicenciasDAO licenciaDAO = new LicenciasDAO();
            try {
                licenciaDAO.insertar(rfc, nombre, apellidoPaterno, apellidoMaterno, 
                        fechaNac, telefono, costo, vig, discapacitado);
                FrmPrincipal frmPrincipal = new FrmPrincipal();
                frmPrincipal.setVisible(true);
                this.dispose();
            } catch (PersistenciaException ex) {
                Logger.getLogger(FrmLicencia.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error");

        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        FrmPrincipal frmPrincial = new FrmPrincipal();
        frmPrincial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxVigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVigenciaActionPerformed
        // TODO add your handling code here:
        //Regresa la opción seleccionada
        String opcion = cbxVigencia.getSelectedItem().toString();
        //Saca el costo dependiendo de las elecciones
        if (chbxSi.isSelected() == false) {
            int costo = numVig.guardar(false, opcion);
            txtCosto.setText(String.valueOf(costo));

        } else if (chbxSi.isSelected() == true) {
            int costo = numVig.guardar(true, opcion);
            txtCosto.setText(String.valueOf(costo));
        }

    }//GEN-LAST:event_cbxVigenciaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String rfc = txtRfc.getText();
        IPersonasDAO personaDAO = new PersonasDAO();

        Persona persona = personaDAO.consultar(rfc);

//Se llenan los campos de texto de manera automática
        txtNombres.setText(persona.getNombres());
        txtApPaterno.setText(persona.getAp_paterno());
        txtApMaterno.setText(persona.getAp_materno());
        //Convierte la fecha en String
        txtFechaNac.setText(persona.getFecha_nacimiento().toString());
        txtTelefono.setText(persona.getTelefono());

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbxVigencia;
    private javax.swing.JCheckBox chbxSi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApMaterno;
    private javax.swing.JLabel lblApPaterno;
    private javax.swing.JLabel lblDatosLicencia;
    private javax.swing.JLabel lblDiscapacitado;
    private javax.swing.JLabel lblDiscapacitado1;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
