
package com.itson.presentacion;

import com.itson.dominio.Persona;


/**
 *
 * @author 
 */
public class FrmPlaca extends javax.swing.JFrame {

    Persona persona = null;
    /**
     * Creates new form Placas
     */
    public FrmPlaca(Persona persona) {
        this.persona = persona;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUsado = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPlacas = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Placas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsado.setBackground(new java.awt.Color(255, 90, 130));
        btnUsado.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnUsado.setForeground(new java.awt.Color(255, 255, 255));
        btnUsado.setText("VEHÍCULO USADO");
        btnUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(255, 90, 130));
        btnNuevo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("VEHÍCULO NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 143, 143));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPlacas.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        lblPlacas.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacas.setText("PLACAS");
        jPanel1.add(lblPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 70));

        btnSalir.setBackground(new java.awt.Color(255, 90, 130));
        btnSalir.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        FrmAutoNuevo frm = new FrmAutoNuevo(persona);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsadoActionPerformed
        // TODO add your handling code here:
        FrmAutoUsado frm = new FrmAutoUsado(persona);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        FrmPrincipal frmPrincial = new FrmPrincipal();
        frmPrincial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPlacas;
    // End of variables declaration//GEN-END:variables
}
