/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

import com.github.lgooddatepicker.components.DatePicker;
import com.itson.utils.TipoTramite;

/**
 *
 * @author alexa
 */
public class FrmReporte extends javax.swing.JFrame {

    DatePicker datePicker = new DatePicker();
    
    /**
     * Creates new form FrmReporte
     */
    public FrmReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        calendarDesde = new com.github.lgooddatepicker.components.CalendarPanel();
        jPanel1 = new javax.swing.JPanel();
        lblReporte = new javax.swing.JLabel();
        lblDesde = new javax.swing.JLabel();
        cmbxTipoTramite = new javax.swing.JComboBox<>();
        lblTipoTramite = new javax.swing.JLabel();
        lblHasta = new javax.swing.JLabel();
        calendarHasta = new com.github.lgooddatepicker.components.CalendarPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTramites = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 168, -1));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));
        getContentPane().add(calendarDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 143, 143));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReporte.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblReporte.setForeground(new java.awt.Color(255, 255, 255));
        lblReporte.setText("REPORTE DE TRÁMITES");
        jPanel1.add(lblReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 90));

        lblDesde.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblDesde.setText("Desde:");
        getContentPane().add(lblDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        cmbxTipoTramite.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        cmbxTipoTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licencia", "Placas" }));
        getContentPane().add(cmbxTipoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 170, -1));

        lblTipoTramite.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblTipoTramite.setText("Tipo de trámite:");
        getContentPane().add(lblTipoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblHasta.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblHasta.setText("Hasta:");
        getContentPane().add(lblHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));
        getContentPane().add(calendarHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        tblTramites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha de emisión", "Nombres", "Tipo", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTramites);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 690, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.CalendarPanel calendarDesde;
    private com.github.lgooddatepicker.components.CalendarPanel calendarHasta;
    private javax.swing.JComboBox<String> cmbxTipoTramite;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JLabel lblTipoTramite;
    private javax.swing.JTable tblTramites;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
